# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 26 Feb 2021 05:27:13 +0000
*               @ALL          1
*               @user         8
