<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Fri, 26 Feb 2021 05:27:13 +0000
 */
$conf['title'] = 'Bible Study';
$conf['lang'] = 'ja';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
