# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Fri, 26 Feb 2021 05:27:13 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

superuser:$2y$10$mpjovxSQ4YAiixU06Tc35eYPvuuTK7Dp0OqmHT6bV4hAAoRTtn7zG:Masaru Kitajima:thirstytraveler@mac.com:admin,user
